
tasks:
  - init: npm install
    command: npm run dev
    name: Development server

  - name: Extension building
    command: echo "Run 'npm run build && cd dist && zip -r ../techlingo-wiki-extension.zip *' to build and package extension"

  - name: SSH Setup for Cursor
    command: |
      # Generate SSH key if it doesn't exist
      if [ ! -f ~/.ssh/id_ed25519 ]; then
        mkdir -p ~/.ssh
        ssh-keygen -t ed25519 -C "gitpod-cursor-connection" -f ~/.ssh/id_ed25519 -N ""
        chmod 600 ~/.ssh/id_ed25519
      fi
      
      # Display connection information in a more visible format
      echo ""
      echo "==========================================="
      echo "        CURSOR SSH CONNECTION SETUP        "
      echo "==========================================="
      echo ""
      echo "1. Copy your public SSH key:"
      cat ~/.ssh/id_ed25519.pub
      echo ""
      echo "2. Cursor connection details:"
      echo "   Host: $(gp url 22 | sed 's/https:\/\///')"
      echo "   Port: 22"
      echo "   Username: gitpod"
      echo ""
      echo "3. In Cursor, go to Settings > SSH > Add Remote"
      echo "   - Enter the host and port above"
      echo "   - Paste your SSH key when prompted"
      echo ""
      echo "4. Test your connection with:"
      echo "   ssh -T gitpod@$(gp url 22 | sed 's/https:\/\///')"
      echo ""
      echo "==========================================="
      
      # Keep SSH server running
      gp ports expose 22

ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
  - port: 22
    visibility: public
    onOpen: ignore
  - port: 3000
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
